// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.StorageComponent
{
    [StorageComponentResourceType("storage-component:index:StorageComponent")]
    public partial class StorageComponent : global::Pulumi.ComponentResource
    {
        [Output("containerName")]
        public Output<string> ContainerName { get; private set; } = null!;

        [Output("storageAccountName")]
        public Output<string> StorageAccountName { get; private set; } = null!;


        /// <summary>
        /// Create a StorageComponent resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public StorageComponent(string name, StorageComponentArgs? args = null, ComponentResourceOptions? options = null)
            : base("storage-component:index:StorageComponent", name, args ?? new StorageComponentArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class StorageComponentArgs : global::Pulumi.ResourceArgs
    {
        [Input("baseName")]
        public Input<string>? BaseName { get; set; }

        [Input("resourceGroupName")]
        public Input<string>? ResourceGroupName { get; set; }

        public StorageComponentArgs()
        {
        }
        public static new StorageComponentArgs Empty => new StorageComponentArgs();
    }
}
